# Generated by Django 5.2.2 on 2025-06-15 00:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingEmailChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_email', models.EmailField(max_length=254)),
                ('token', models.CharField(max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pending_email_change', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pending Email Change',
                'verbose_name_plural': 'Pending Email Changes',
                'indexes': [models.Index(fields=['token'], name='account_pen_token_c47b4b_idx'), models.Index(fields=['expires_at'], name='account_pen_expires_228a47_idx')],
            },
        ),
    ]
