# Generated by Django 5.2.2 on 2025-06-15 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_pendingemailchange'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_password_change',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Last Password Change'),
        ),
    ]
