# Generated by Django 5.2.2 on 2025-06-22 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_user_last_password_change'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Super Admin'), ('businessman', 'Businessman')], default='businessman', max_length=20),
        ),
    ]
