# docker-compose.dev.yml
services:
  server:
    volumes:
      - .:/app
      - ./.env:/app/.env
    environment:
      - DJANGO_ENV=development
      - DEBUG=1
    
    # IMPORTANT: don't override command; entrypoint handles dev runserver
    build:
      context: .
      args:
        REMOVE_MIGRATIONS: "false"   # keep migrations in repo; dev uses --fake-initial anyway