# Generated by Django 5.2.2 on 2025-07-13 10:00

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Customer's full name", max_length=100, verbose_name='Name')),
                ('email', models.EmailField(blank=True, help_text="Customer's email address", max_length=254, null=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, help_text="Customer's contact number", max_length=20, null=True, verbose_name='Phone Number')),
                ('orders_count', models.PositiveIntegerField(default=0, help_text='Total number of orders placed by this customer', verbose_name='Orders Count')),
                ('total_spent', models.DecimalField(decimal_places=2, default=0, help_text='Total amount spent by this customer', max_digits=10, verbose_name='Total Spent')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', help_text='Customer account status', max_length=10, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(help_text='Unique identifier for the order', max_length=20, unique=True, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Order Number')),
                ('items', models.PositiveIntegerField(help_text='Number of items in this order', verbose_name='Items Count')),
                ('total', models.DecimalField(decimal_places=2, help_text='Total amount for this order', max_digits=10, verbose_name='Order Total')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', help_text='Current status of the order', max_length=20, verbose_name='Order Status')),
                ('source', models.CharField(choices=[('facebook', 'Facebook'), ('whatsapp', 'Whatsapp'), ('manual', 'Manual')], default='manual', help_text='From which source the order is from', max_length=20, verbose_name='Source')),
                ('payment_status', models.CharField(choices=[('paid', 'Paid'), ('pending', 'Pending'), ('refunded', 'Refunded')], default='pending', help_text='Current payment status of the order', max_length=20, verbose_name='Payment Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('customer', models.ForeignKey(help_text='Customer who placed this order', on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='customer.customer', verbose_name='Customer')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['name'], name='customer_cu_name_600631_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['email'], name='customer_cu_email_7d0597_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['status'], name='customer_cu_status_98075e_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_number'], name='customer_or_order_n_1eea27_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status'], name='customer_or_status_94fde1_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['payment_status'], name='customer_or_payment_77b69a_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['customer'], name='customer_or_custome_bd3a70_idx'),
        ),
    ]
