# Generated by Django 5.2.2 on 2025-08-09 01:10

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='customer',
            name='customer_cu_email_7d0597_idx',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='email',
        ),
        migrations.AddField(
            model_name='customer',
            name='area',
            field=models.CharField(blank=True, help_text='Specific area or street address', max_length=255, null=True, verbose_name='Area/Street Address'),
        ),
        migrations.AddField(
            model_name='customer',
            name='city',
            field=models.CharField(default='Unknown', help_text="Customer's city", max_length=100, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='customer',
            name='police_station',
            field=models.CharField(default='Unknown', help_text='Nearest police station for address reference', max_length=100, verbose_name='Police Station'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text="Customer's contact number (e.g., +12125552368)", max_length=128, null=True, region=None, verbose_name='Phone Number'),
        ),
    ]
