# Generated by Django 5.2.1 on 2025-05-31 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_alter_customer_options_alter_order_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='source',
            field=models.CharField(choices=[('facebook', 'Facebook'), ('whatsapp', 'Whatsapp'), ('manual', 'Manual')], default='manual', help_text='From which source the order is from', max_length=20, verbose_name='Source'),
        ),
    ]
