# Generated by Django 5.2.2 on 2025-08-09 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_remove_customer_customer_cu_email_7d0597_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='city',
            field=models.CharField(help_text="Customer's city", max_length=100, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='police_station',
            field=models.CharField(help_text='Nearest police station for address reference', max_length=100, verbose_name='Police Station'),
        ),
    ]
