# Generated by Django 5.2.2 on 2025-08-09 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_alter_customer_city_alter_customer_police_station'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='police_station',
            field=models.CharField(help_text='Nearest police station for address reference', max_length=255, verbose_name='Police Station'),
        ),
    ]
