# Generated by Django 5.2.2 on 2025-08-09 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_facebookintegration_app_id_and_more'),
        ('customer', '0004_alter_customer_police_station'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='customer.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='business.product')),
            ],
            options={
                'unique_together': {('order', 'product')},
            },
        ),
    ]
