# Generated by Django 5.2.2 on 2025-08-09 08:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(help_text='Unique identifier for the order', max_length=30, unique=True, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Order Number'),
        ),
    ]
