# Generated by Django 5.2.2 on 2025-06-23 05:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_model', models.CharField(choices=[('gemini-pro', 'Gemini Pro'), ('gemini-ultra', 'Gemini Ultra'), ('custom', 'Custom Model')], default='gemini-pro', max_length=20)),
                ('api_key', models.CharField(max_length=255)),
                ('response_tone', models.CharField(choices=[('friendly', 'Friendly and Casual'), ('professional', 'Professional'), ('formal', 'Formal'), ('helpful', 'Helpful and Informative')], default='friendly', max_length=20)),
                ('brand_persona', models.TextField()),
                ('auto_respond', models.BooleanField(default=True)),
                ('generate_suggestions', models.BooleanField(default=True)),
                ('human_handoff', models.BooleanField(default=True)),
                ('learn_from_history', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_config', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
