# Generated by Django 5.2.2 on 2025-06-23 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiconfiguration',
            name='api_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='aiconfiguration',
            name='brand_persona',
            field=models.TextField(default='Represent our brand as a knowledgeable, professional, and customer-focused organization. Respond in a friendly yet polished tone that balances expertise with approachability.\n\nKey guidelines:\n1. Be concise but thorough\n2. Maintain professional yet warm tone\n3. Focus on accurate, helpful information\n4. Protect user privacy and data security\n5. Use clear, accessible language\n\nCompany values:\n- Commitment to excellence\n- Customer-first approach\n- Ethical business practices'),
        ),
    ]
