# Generated by Django 5.2.2 on 2025-07-25 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiconfiguration',
            name='total_input_tokens',
            field=models.PositiveBigIntegerField(default=0, help_text='Lifetime count of input tokens used'),
        ),
        migrations.AddField(
            model_name='aiconfiguration',
            name='total_output_tokens',
            field=models.PositiveBigIntegerField(default=0, help_text='Lifetime count of output tokens generated'),
        ),
        migrations.AddField(
            model_name='aiconfiguration',
            name='total_tokens',
            field=models.PositiveBigIntegerField(default=0, help_text='Lifetime total tokens used'),
        ),
    ]
