# Generated by Django 5.2.2 on 2025-06-25 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_alter_aiconfiguration_api_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiconfiguration',
            name='ai_model',
            field=models.CharField(choices=[('gemini-2.0-flash', 'Gemini 2.0 Flash'), ('gemini-ultra', 'Gemini Ultra'), ('custom', 'Custom Model')], default='gemini-2.0-flash', max_length=20),
        ),
    ]
