# Generated by Django 5.2.2 on 2025-07-13 10:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_reply', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(choices=[('customer', 'Customer'), ('business', 'Business'), ('ai', 'AI')], default='business', max_length=10)),
                ('message', models.TextField(blank=True, null=True)),
                ('media_id', models.CharField(blank=True, max_length=255, null=True)),
                ('media_type', models.CharField(blank=True, max_length=50, null=True)),
                ('messenger_media_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('messenger_media_file', models.FileField(blank=True, null=True, upload_to='messenger_images/')),
                ('download_status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='completed', max_length=10, null=True)),
                ('contacts', models.JSONField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='messaging.conversation')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='SocialMediaUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Name of the social media user', max_length=100, verbose_name='Name')),
                ('social_media_id', models.CharField(help_text='Unique identifier from the social platform', max_length=50, verbose_name='Social Media ID')),
                ('avatar_url', models.URLField(blank=True, help_text="URL to the socialuser's profile picture", max_length=500, null=True, verbose_name='Avatar URL')),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('whatsapp', 'WhatsApp'), ('instagram', 'Instagram'), ('twitter', 'Twitter')], db_index=True, help_text='Social media platform', max_length=20, verbose_name='Platform')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('customer', models.ForeignKey(blank=True, help_text='Linked customer account', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='social_media_users', to='customer.customer', verbose_name='Customer')),
            ],
            options={
                'verbose_name': 'Social Media User',
                'verbose_name_plural': 'Social Media Users',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='conversation',
            name='socialuser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='messaging.socialmediauser'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('message', 'New Message'), ('conversation', 'New Conversation'), ('status', 'Message Status')], default='message', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='messaging.conversation')),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='messaging.chatmessage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='messaging_n_user_id_bd7d88_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='socialmediauser',
            index=models.Index(fields=['platform', 'social_media_id'], name='messaging_s_platfor_1e5831_idx'),
        ),
        migrations.AddConstraint(
            model_name='socialmediauser',
            constraint=models.UniqueConstraint(fields=('platform', 'social_media_id'), name='unique_social_media_user'),
        ),
    ]
