# Generated by Django 5.2.1 on 2025-05-29 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_alter_customer_options_alter_order_options_and_more'),
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='socialmediauser',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Social Media User', 'verbose_name_plural': 'Social Media Users'},
        ),
        migrations.AddField(
            model_name='socialmediauser',
            name='customer',
            field=models.ForeignKey(blank=True, help_text='Linked customer account', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='social_media_users', to='customer.customer', verbose_name='Customer'),
        ),
        migrations.AddField(
            model_name='socialmediauser',
            name='platform',
            field=models.CharField(choices=[('facebook', 'Facebook'), ('whatsapp', 'WhatsApp'), ('instagram', 'Instagram'), ('twitter', 'Twitter')], db_index=True, default='facebook', help_text='Social media platform', max_length=20, verbose_name='Platform'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='socialmediauser',
            name='avatar_url',
            field=models.URLField(blank=True, help_text="URL to the user's profile picture", max_length=500, null=True, verbose_name='Avatar URL'),
        ),
        migrations.AlterField(
            model_name='socialmediauser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='socialmediauser',
            name='name',
            field=models.CharField(blank=True, help_text='Name of the social media user', max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='socialmediauser',
            name='social_media_id',
            field=models.CharField(help_text='Unique identifier from the social platform', max_length=50, verbose_name='Social Media ID'),
        ),
        migrations.AlterField(
            model_name='socialmediauser',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterUniqueTogether(
            name='socialmediauser',
            unique_together={('platform', 'customer')},
        ),
        migrations.AddIndex(
            model_name='socialmediauser',
            index=models.Index(fields=['platform', 'social_media_id'], name='messaging_s_platfor_1e5831_idx'),
        ),
    ]
