# Generated by Django 5.2.1 on 2025-05-29 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_alter_customer_options_alter_order_options_and_more'),
        ('messaging', '0002_alter_socialmediauser_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='socialmediauser',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='socialmediauser',
            constraint=models.UniqueConstraint(fields=('platform', 'social_media_id'), name='unique_social_media_user'),
        ),
    ]
