# Generated by Django 5.2.1 on 2025-05-29 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_alter_customer_options_alter_order_options_and_more'),
        ('messaging', '0003_alter_socialmediauser_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='socialmediauser',
            name='unique_social_media_user',
        ),
        migrations.AddConstraint(
            model_name='socialmediauser',
            constraint=models.UniqueConstraint(condition=models.Q(('customer__isnull', False)), fields=('platform', 'social_media_id'), name='unique_social_user_per_platform_and_id_with_customer'),
        ),
    ]
