# Generated by Django 5.2.1 on 2025-05-29 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_alter_customer_options_alter_order_options_and_more'),
        ('messaging', '0004_remove_socialmediauser_unique_social_media_user_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='socialmediauser',
            name='unique_social_user_per_platform_and_id_with_customer',
        ),
        migrations.AddConstraint(
            model_name='socialmediauser',
            constraint=models.UniqueConstraint(fields=('platform', 'social_media_id'), name='unique_social_media_user'),
        ),
    ]
