# Generated by Django 5.2.1 on 2025-05-29 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0005_remove_socialmediauser_unique_social_user_per_platform_and_id_with_customer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='channel',
        ),
    ]
