# Generated by Django 5.2.2 on 2025-06-10 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0007_chatmessage_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='media_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='media_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='media_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
