# Generated by Django 5.2.2 on 2025-06-10 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0008_remove_chatmessage_timestamp_chatmessage_media_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='media_url',
        ),
    ]
