# Generated by Django 5.2.2 on 2025-06-10 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0009_remove_chatmessage_media_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='contacts_data',
            field=models.JSONField(blank=True, default={}, null=True),
        ),
    ]
