# Generated by Django 5.2.2 on 2025-06-10 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0011_alter_chatmessage_contacts_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='contacts_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
