# Generated by Django 5.2.2 on 2025-06-10 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0012_alter_chatmessage_contacts_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatmessage',
            old_name='contacts_data',
            new_name='contacts',
        ),
    ]
