# Generated by Django 5.2.2 on 2025-06-11 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0013_rename_contacts_data_chatmessage_contacts'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='messenger_media_file',
            field=models.FileField(blank=True, null=True, upload_to='messenger_images/'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='messenger_media_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
