# Generated by Django 5.2.2 on 2025-06-11 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0014_chatmessage_messenger_media_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='messenger_media_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
