# Generated by Django 5.2.2 on 2025-06-12 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0015_alter_chatmessage_messenger_media_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='download_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='completed', max_length=10, null=True),
        ),
    ]
