# Generated by Django 5.2.2 on 2025-06-17 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0017_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='extra_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('message', 'New Message'), ('conversation', 'New Conversation'), ('status', 'Message Status')], default='message', max_length=20),
        ),
    ]
