# Generated by Django 5.2.2 on 2025-06-28 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0018_notification_extra_data_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversation',
            old_name='user',
            new_name='socialuser',
        ),
        migrations.AlterField(
            model_name='socialmediauser',
            name='avatar_url',
            field=models.URLField(blank=True, help_text="URL to the socialuser's profile picture", max_length=500, null=True, verbose_name='Avatar URL'),
        ),
    ]
