# Generated by Django 5.2.2 on 2025-08-05 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_productfaq'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebookintegration',
            name='app_id',
            field=models.CharField(blank=True, help_text='The Facebook App ID for the integration', max_length=255, null=True, verbose_name='Facebook App ID'),
        ),
        migrations.AddField(
            model_name='facebookintegration',
            name='app_secret',
            field=models.CharField(blank=True, help_text='The Facebook App Secret for the integration', max_length=255, null=True, verbose_name='Facebook App Secret'),
        ),
    ]
