# Generated by Django 5.2.2 on 2025-06-28 09:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_productcategory_product'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Service Name')),
                ('description', models.TextField(blank=True, verbose_name='Detailed Description')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Starting Price')),
                ('duration_minutes', models.PositiveIntegerField(help_text='Approximate time needed to complete the service', verbose_name='Duration (minutes)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active Service')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to=settings.AUTH_USER_MODEL, verbose_name='Service Provider')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
