# Generated by Django 5.2.2 on 2025-07-04 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_service'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facebookintegration',
            options={'verbose_name': 'Facebook Integration', 'verbose_name_plural': 'Facebook Integrations'},
        ),
        migrations.AlterModelOptions(
            name='whatsappintegration',
            options={'verbose_name': 'WhatsApp Integration', 'verbose_name_plural': 'WhatsApp Integrations'},
        ),
        migrations.AddField(
            model_name='facebookintegration',
            name='platform_id',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='whatsappintegration',
            name='platform_id',
            field=models.CharField(blank=True, null=True),
        ),
    ]
