# Generated by Django 5.2.2 on 2025-07-04 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0005_alter_facebookintegration_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebookintegration',
            name='verify_token',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='whatsappintegration',
            name='verify_token',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='facebookintegration',
            name='access_token',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='whatsappintegration',
            name='access_token',
            field=models.CharField(blank=True, null=True),
        ),
    ]
