# Generated by Django 5.2.2 on 2025-07-04 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0006_facebookintegration_verify_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facebookintegration',
            name='access_token',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='facebookintegration',
            name='verify_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='whatsappintegration',
            name='access_token',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='whatsappintegration',
            name='verify_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
